[project]
name = "okidokey-toolkit"
version = "3.0.0"
description = "OkidoKey toolkit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "csvkit>=2.2.0",
    "natsort>=8.4.0",
    "pypinyin>=0.55.0",
    "scrapy>=2.14.1",
    "tqdm>=4.67.1",
]
